#ifndef MENTAL_H
#define MENTAL_H


enum MentalStructureType
{
    MENTAL_STRUCTURE_TYPE_APPLICATION_INFO = 0,
    MENTAL_STRUCTURE_TYPE_APPLICATION = 1,

    MENTAL_STRUCTURE_TYPE_WINDOW_MANAGER_INFO = 2,
    MENTAL_STRUCTURE_TYPE_WINDOW_MANAGER = 3,

    MENTAL_STRUCTURE_TYPE_RENDERER_INFO = 4,
    MENTAL_STRUCTURE_TYPE_RENDERER = 5,

    MENTAL_STRUCTYRE_TYPE_RENDER_POOL_INFO = 6,
    MENTAL_STRUCTURE_TYPE_RENDER_POOL = 7,

    MENTAL_STRUCTURE_TYPE_OBJECT_INFO = 8,
    MENTAL_STRUCTURE_TYPE_OBJECT = 9,

    MENTAL_STRUCTURE_TYPE_MATERIAL_INFO = 9,
    MENTAL_STRUCTURE_TYPE_MATERIAL = 10,

    MENTAL_STRUCTURE_TYPE_SHADER_INFO = 10,
    MENTAL_STRUCTURE_TYPE_SHADER = 11,
};


#endif // MENTAL_H